from html import escape

from flask import current_app
from flask_mail import Message

from extensions import mail


def send_accident_email(
    receiver_email,
    driver_name,
    latitude,
    longitude,
    hospital_name,
    severity,
    impact_force=None,
    description=None,
    contact_name=None
):
    """
    Send a professional accident-alert email.

    The last three parameters are optional, so older calls to this
    function will continue to work.
    """

    receiver_email = str(receiver_email or "").strip()
    driver_name = str(
        driver_name or "DriveShield AI User"
    ).strip()

    hospital_name = str(
        hospital_name or "Nearest hospital not available"
    ).strip()

    severity = str(
        severity or "UNKNOWN"
    ).strip().upper()

    description = str(
        description or "Accident detected automatically."
    ).strip()

    contact_name = str(
        contact_name or "Emergency Contact"
    ).strip()

    if not receiver_email:
        current_app.logger.error(
            "Email sending failed: receiver email is empty."
        )
        return False

    try:
        latitude_value = float(latitude)
        longitude_value = float(longitude)
    except (TypeError, ValueError):
        current_app.logger.error(
            "Email sending failed: invalid GPS coordinates."
        )
        return False

    maps_link = (
        "https://www.google.com/maps/search/"
        f"?api=1&query={latitude_value},{longitude_value}"
    )

    impact_text = "Not available"

    if impact_force is not None:
        try:
            impact_text = f"{float(impact_force):.2f} G"
        except (TypeError, ValueError):
            impact_text = "Not available"

    subject = (
        f"DriveShield AI Emergency Alert - {severity} Severity"
    )

    plain_body = f"""
DriveShield AI - Emergency Accident Alert

Hello {contact_name},

A possible accident involving {driver_name} has been detected.

ACCIDENT DETAILS

Driver Name:
{driver_name}

Severity:
{severity}

Impact Force:
{impact_text}

Description:
{description}

CURRENT LOCATION

Latitude:
{latitude_value}

Longitude:
{longitude_value}

Google Maps:
{maps_link}

NEAREST HOSPITAL

{hospital_name}

Please contact the driver immediately and arrange emergency assistance if required.

This is an automated safety alert generated by DriveShield AI.
""".strip()

    safe_contact_name = escape(contact_name)
    safe_driver_name = escape(driver_name)
    safe_severity = escape(severity)
    safe_impact_text = escape(impact_text)
    safe_description = escape(description)
    safe_hospital_name = escape(hospital_name)
    safe_maps_link = escape(
        maps_link,
        quote=True
    )

    html_body = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    <title>DriveShield AI Emergency Alert</title>
</head>

<body style="
    margin: 0;
    padding: 0;
    background-color: #f3f6fb;
    font-family: Arial, Helvetica, sans-serif;
    color: #1f2937;
">
    <table
        role="presentation"
        width="100%"
        cellspacing="0"
        cellpadding="0"
        border="0"
        style="background-color: #f3f6fb;"
    >
        <tr>
            <td
                align="center"
                style="padding: 24px 12px;"
            >
                <table
                    role="presentation"
                    width="100%"
                    cellspacing="0"
                    cellpadding="0"
                    border="0"
                    style="
                        max-width: 640px;
                        background-color: #ffffff;
                        border-radius: 18px;
                        overflow: hidden;
                        box-shadow: 0 8px 30px rgba(15, 23, 42, 0.12);
                    "
                >
                    <tr>
                        <td style="
                            padding: 28px 24px;
                            background: linear-gradient(
                                135deg,
                                #b91c1c,
                                #ef4444
                            );
                            text-align: center;
                            color: #ffffff;
                        ">
                            <div style="
                                font-size: 38px;
                                line-height: 1;
                                margin-bottom: 10px;
                            ">
                                🚨
                            </div>

                            <h1 style="
                                margin: 0;
                                font-size: 26px;
                                line-height: 1.25;
                            ">
                                Emergency Accident Alert
                            </h1>

                            <p style="
                                margin: 9px 0 0;
                                font-size: 14px;
                                opacity: 0.9;
                            ">
                                Generated automatically by DriveShield AI
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 26px 24px 10px;">
                            <p style="
                                margin: 0 0 12px;
                                font-size: 16px;
                                line-height: 1.6;
                            ">
                                Hello <strong>{safe_contact_name}</strong>,
                            </p>

                            <p style="
                                margin: 0;
                                font-size: 16px;
                                line-height: 1.65;
                            ">
                                A possible accident involving
                                <strong>{safe_driver_name}</strong>
                                has been detected. Please review the
                                details below and contact the driver
                                immediately.
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 16px 24px 8px;">
                            <table
                                role="presentation"
                                width="100%"
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                style="
                                    border: 1px solid #e5e7eb;
                                    border-radius: 14px;
                                    overflow: hidden;
                                "
                            >
                                <tr>
                                    <td
                                        colspan="2"
                                        style="
                                            padding: 14px 16px;
                                            background-color: #fff1f2;
                                            color: #991b1b;
                                            font-size: 17px;
                                            font-weight: bold;
                                        "
                                    >
                                        Accident Details
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        width: 38%;
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                        font-weight: bold;
                                        color: #4b5563;
                                    ">
                                        Driver
                                    </td>

                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                    ">
                                        {safe_driver_name}
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                        font-weight: bold;
                                        color: #4b5563;
                                    ">
                                        Severity
                                    </td>

                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                    ">
                                        <span style="
                                            display: inline-block;
                                            padding: 5px 10px;
                                            border-radius: 999px;
                                            background-color: #fee2e2;
                                            color: #991b1b;
                                            font-weight: bold;
                                        ">
                                            {safe_severity}
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                        font-weight: bold;
                                        color: #4b5563;
                                    ">
                                        Impact Force
                                    </td>

                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                    ">
                                        {safe_impact_text}
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                        font-weight: bold;
                                        color: #4b5563;
                                        vertical-align: top;
                                    ">
                                        Description
                                    </td>

                                    <td style="
                                        padding: 12px 16px;
                                        border-top: 1px solid #e5e7eb;
                                        line-height: 1.55;
                                    ">
                                        {safe_description}
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 16px 24px 8px;">
                            <table
                                role="presentation"
                                width="100%"
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                style="
                                    border: 1px solid #e5e7eb;
                                    border-radius: 14px;
                                    overflow: hidden;
                                "
                            >
                                <tr>
                                    <td style="
                                        padding: 14px 16px;
                                        background-color: #eff6ff;
                                        color: #1d4ed8;
                                        font-size: 17px;
                                        font-weight: bold;
                                    ">
                                        Current Location
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding: 16px;
                                        line-height: 1.65;
                                    ">
                                        <strong>Latitude:</strong>
                                        {latitude_value}
                                        <br>

                                        <strong>Longitude:</strong>
                                        {longitude_value}
                                    </td>
                                </tr>

                                <tr>
                                    <td
                                        align="center"
                                        style="padding: 0 16px 18px;"
                                    >
                                        <a
                                            href="{safe_maps_link}"
                                            style="
                                                display: inline-block;
                                                padding: 12px 22px;
                                                border-radius: 10px;
                                                background-color: #2563eb;
                                                color: #ffffff;
                                                text-decoration: none;
                                                font-weight: bold;
                                            "
                                        >
                                            Open Location in Google Maps
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 16px 24px 8px;">
                            <table
                                role="presentation"
                                width="100%"
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                style="
                                    border: 1px solid #e5e7eb;
                                    border-radius: 14px;
                                    overflow: hidden;
                                "
                            >
                                <tr>
                                    <td style="
                                        padding: 14px 16px;
                                        background-color: #ecfdf5;
                                        color: #047857;
                                        font-size: 17px;
                                        font-weight: bold;
                                    ">
                                        Nearest Hospital
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding: 16px;
                                        font-size: 16px;
                                        line-height: 1.55;
                                    ">
                                        {safe_hospital_name}
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 20px 24px 28px;">
                            <div style="
                                padding: 16px;
                                border-radius: 12px;
                                background-color: #fff7ed;
                                color: #9a3412;
                                font-size: 15px;
                                line-height: 1.6;
                                text-align: center;
                            ">
                                Please contact the driver immediately and
                                arrange emergency assistance when required.
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding: 18px 24px;
                            background-color: #111827;
                            color: #d1d5db;
                            text-align: center;
                            font-size: 12px;
                            line-height: 1.6;
                        ">
                            This automated alert was generated by
                            DriveShield AI.
                            <br>
                            Do not reply to this email.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
""".strip()

    try:
        sender_email = current_app.config.get(
            "MAIL_USERNAME"
        )

        if not sender_email:
            raise ValueError(
                "MAIL_USERNAME is not configured."
            )

        message = Message(
            subject=subject,
            sender=sender_email,
            recipients=[receiver_email],
            body=plain_body,
            html=html_body
        )

        mail.send(message)

        current_app.logger.info(
            "Accident alert sent successfully to %s",
            receiver_email
        )

        return True

    except Exception as error:
        current_app.logger.exception(
            "Accident email sending failed for %s: %s",
            receiver_email,
            error
        )

        return False