from html import escape

import requests
from flask import current_app


BREVO_EMAIL_API_URL = "https://api.brevo.com/v3/smtp/email"


def send_accident_email(
    receiver_email,
    driver_name,
    latitude,
    longitude,
    hospital_name,
    severity,
    impact_force=None,
    description=None,
    contact_name=None
):
    """
    Send an accident-alert email through the Brevo HTTPS API.

    The function signature remains compatible with the existing
    DriveShield AI accident workflow.
    """

    receiver_email = str(
        receiver_email or ""
    ).strip()

    driver_name = str(
        driver_name or "DriveShield AI User"
    ).strip()

    hospital_name = str(
        hospital_name
        or "Nearest hospital not available"
    ).strip()

    severity = str(
        severity or "UNKNOWN"
    ).strip().upper()

    description = str(
        description
        or "Accident detected automatically."
    ).strip()

    contact_name = str(
        contact_name or "Emergency Contact"
    ).strip()

    if not receiver_email:
        current_app.logger.error(
            "Brevo email sending failed: "
            "receiver email is empty."
        )
        return False

    try:
        latitude_value = float(latitude)
        longitude_value = float(longitude)

    except (TypeError, ValueError):
        current_app.logger.error(
            "Brevo email sending failed: "
            "invalid GPS coordinates."
        )
        return False

    maps_link = (
        "https://www.google.com/maps/search/"
        f"?api=1&query="
        f"{latitude_value},{longitude_value}"
    )

    impact_text = "Not available"

    if impact_force is not None:

        try:
            impact_text = (
                f"{float(impact_force):.2f} G"
            )

        except (TypeError, ValueError):
            impact_text = "Not available"

    subject = (
        "DriveShield AI Emergency Alert - "
        f"{severity} Severity"
    )

    plain_body = f"""
DriveShield AI - Emergency Accident Alert

Hello {contact_name},

A possible accident involving {driver_name} has been detected.

ACCIDENT DETAILS

Driver Name:
{driver_name}

Severity:
{severity}

Impact Force:
{impact_text}

Description:
{description}

CURRENT LOCATION

Latitude:
{latitude_value}

Longitude:
{longitude_value}

Google Maps:
{maps_link}

NEAREST HOSPITAL

{hospital_name}

Please contact the driver immediately and arrange emergency assistance if required.

This is an automated safety alert generated by DriveShield AI.
""".strip()

    safe_contact_name = escape(
        contact_name
    )

    safe_driver_name = escape(
        driver_name
    )

    safe_severity = escape(
        severity
    )

    safe_impact_text = escape(
        impact_text
    )

    safe_description = escape(
        description
    )

    safe_hospital_name = escape(
        hospital_name
    )

    safe_maps_link = escape(
        maps_link,
        quote=True
    )

    html_body = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    <title>DriveShield AI Emergency Alert</title>
</head>

<body style="
    margin:0;
    padding:0;
    background:#f3f6fb;
    font-family:Arial,Helvetica,sans-serif;
    color:#1f2937;
">
    <table
        role="presentation"
        width="100%"
        cellspacing="0"
        cellpadding="0"
        border="0"
        style="background:#f3f6fb;"
    >
        <tr>
            <td
                align="center"
                style="padding:24px 12px;"
            >
                <table
                    role="presentation"
                    width="100%"
                    cellspacing="0"
                    cellpadding="0"
                    border="0"
                    style="
                        max-width:640px;
                        background:#ffffff;
                        border-radius:18px;
                        overflow:hidden;
                        box-shadow:
                            0 8px 30px
                            rgba(15,23,42,0.12);
                    "
                >
                    <tr>
                        <td style="
                            padding:28px 24px;
                            background:#dc2626;
                            text-align:center;
                            color:#ffffff;
                        ">
                            <div style="
                                font-size:38px;
                                margin-bottom:10px;
                            ">
                                🚨
                            </div>

                            <h1 style="
                                margin:0;
                                font-size:26px;
                            ">
                                Emergency Accident Alert
                            </h1>

                            <p style="
                                margin:9px 0 0;
                                font-size:14px;
                            ">
                                Generated automatically by
                                DriveShield AI
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding:26px 24px 10px;
                            font-size:16px;
                            line-height:1.65;
                        ">
                            Hello
                            <strong>
                                {safe_contact_name}
                            </strong>,
                            <br><br>

                            A possible accident involving
                            <strong>
                                {safe_driver_name}
                            </strong>
                            has been detected.
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding:16px 24px 8px;
                        ">
                            <table
                                role="presentation"
                                width="100%"
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                style="
                                    border:1px solid #e5e7eb;
                                    border-radius:14px;
                                "
                            >
                                <tr>
                                    <td
                                        colspan="2"
                                        style="
                                            padding:14px 16px;
                                            background:#fff1f2;
                                            color:#991b1b;
                                            font-size:17px;
                                            font-weight:bold;
                                        "
                                    >
                                        Accident Details
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        width:38%;
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                        font-weight:bold;
                                    ">
                                        Driver
                                    </td>

                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                    ">
                                        {safe_driver_name}
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                        font-weight:bold;
                                    ">
                                        Severity
                                    </td>

                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                    ">
                                        {safe_severity}
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                        font-weight:bold;
                                    ">
                                        Impact Force
                                    </td>

                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                    ">
                                        {safe_impact_text}
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                        font-weight:bold;
                                    ">
                                        Description
                                    </td>

                                    <td style="
                                        padding:12px 16px;
                                        border-top:
                                            1px solid #e5e7eb;
                                    ">
                                        {safe_description}
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding:16px 24px 8px;
                        ">
                            <table
                                role="presentation"
                                width="100%"
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                style="
                                    border:1px solid #e5e7eb;
                                    border-radius:14px;
                                "
                            >
                                <tr>
                                    <td style="
                                        padding:14px 16px;
                                        background:#eff6ff;
                                        color:#1d4ed8;
                                        font-size:17px;
                                        font-weight:bold;
                                    ">
                                        Current Location
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding:16px;
                                        line-height:1.65;
                                    ">
                                        <strong>
                                            Latitude:
                                        </strong>
                                        {latitude_value}
                                        <br>

                                        <strong>
                                            Longitude:
                                        </strong>
                                        {longitude_value}
                                    </td>
                                </tr>

                                <tr>
                                    <td
                                        align="center"
                                        style="
                                            padding:
                                                0 16px 18px;
                                        "
                                    >
                                        <a
                                            href="{safe_maps_link}"
                                            style="
                                                display:inline-block;
                                                padding:12px 22px;
                                                border-radius:10px;
                                                background:#2563eb;
                                                color:#ffffff;
                                                text-decoration:none;
                                                font-weight:bold;
                                            "
                                        >
                                            Open Location in
                                            Google Maps
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding:16px 24px 8px;
                        ">
                            <table
                                role="presentation"
                                width="100%"
                                cellspacing="0"
                                cellpadding="0"
                                border="0"
                                style="
                                    border:1px solid #e5e7eb;
                                    border-radius:14px;
                                "
                            >
                                <tr>
                                    <td style="
                                        padding:14px 16px;
                                        background:#ecfdf5;
                                        color:#047857;
                                        font-size:17px;
                                        font-weight:bold;
                                    ">
                                        Nearest Hospital
                                    </td>
                                </tr>

                                <tr>
                                    <td style="
                                        padding:16px;
                                        font-size:16px;
                                    ">
                                        {safe_hospital_name}
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding:20px 24px 28px;
                        ">
                            <div style="
                                padding:16px;
                                border-radius:12px;
                                background:#fff7ed;
                                color:#9a3412;
                                text-align:center;
                                line-height:1.6;
                            ">
                                Please contact the driver
                                immediately and arrange
                                emergency assistance when
                                required.
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td style="
                            padding:18px 24px;
                            background:#111827;
                            color:#d1d5db;
                            text-align:center;
                            font-size:12px;
                        ">
                            This automated alert was
                            generated by DriveShield AI.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
""".strip()

    try:
        api_key = str(
            current_app.config.get(
                "BREVO_API_KEY"
            )
            or ""
        ).strip()

        sender_email = str(
            current_app.config.get(
                "BREVO_SENDER_EMAIL"
            )
            or ""
        ).strip()

        sender_name = str(
            current_app.config.get(
                "BREVO_SENDER_NAME"
            )
            or "DriveShield AI"
        ).strip()

        reply_to = str(
            current_app.config.get(
                "BREVO_REPLY_TO"
            )
            or ""
        ).strip()

        if not api_key:
            raise ValueError(
                "BREVO_API_KEY is not configured."
            )

        if not sender_email:
            raise ValueError(
                "BREVO_SENDER_EMAIL is not configured."
            )

        headers = {
            "accept": "application/json",
            "api-key": api_key,
            "content-type": "application/json"
        }

        email_payload = {
            "sender": {
                "name": sender_name,
                "email": sender_email
            },
            "to": [
                {
                    "email": receiver_email,
                    "name": contact_name
                }
            ],
            "subject": subject,
            "textContent": plain_body,
            "htmlContent": html_body
        }

        if reply_to:
            email_payload["replyTo"] = {
                "email": reply_to,
                "name": sender_name
            }

        response = requests.post(
            BREVO_EMAIL_API_URL,
            headers=headers,
            json=email_payload,
            timeout=25
        )

        if not response.ok:

            response_message = (
                response.text[:500]
                if response.text
                else "No response body"
            )

            raise RuntimeError(
                "Brevo API returned "
                f"HTTP {response.status_code}: "
                f"{response_message}"
            )

        response_data = response.json()

        message_id = (
            response_data.get("messageId")
            or response_data.get("messageIds")
            or "not returned"
        )

        current_app.logger.info(
            "Accident alert accepted by Brevo "
            "for %s. Message ID: %s",
            receiver_email,
            message_id
        )

        return True

    except Exception as error:

        current_app.logger.exception(
            "Accident email sending through "
            "Brevo failed for %s: %s",
            receiver_email,
            error
        )

        return False